### ISSUE TITLE
.

### ISSUE THREAD

**Issue by debeciak** [sa-y0nara/Redmibook-7840HS-Linux#1]
Can you make this but for 7640HS?

**Comment by sa-y0nara** [comment]
Oh,haha!This is the first issue I received in my life,I am happy and I would like to try my best to help you.
Maybe OK,but I can not verify that if it can work on 7640HS because I don't have this machine.
However,the difference between Redmibook 7840HS and 7640HS looks like only it,which means that the other devices are the same.My repository only includes the driver of  the fingerprint scanner、mt7922 and GPU.Although I mentioned 780M in the script, it is actually a common driver that can be used with all Radeon GPUs.So I think it can work on 7640HS directly too.You can have a try.
Hope you can run Ubuntu on your computer without any problem!

**Comment by debeciak** [comment]
Thanks, I also came to that conclusion. Everything works perfect.
